title: Simple Inked
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.946288
  brandStrength: 0.7168459
  lightness: 0.1684588
  brandColors:
    - '#9e9f97'
    - '#020108'
    - '#753229'
    - '#4b4843'
    - '#a35c44'
  rhythmicContrast: 0.3454258
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Simple Inked
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.74018
layout_spectrum: 0.9157706
