name: Simple Inked
favicon: null
layout_spectrum: 0.8998513426631689
typography_spectrum: 0.0579357894603163
title: Simple Inked
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9e9f97'
    - '#020108'
    - '#753229'
    - '#4b4843'
    - '#a35c44'
  brandStrength: 0.3125
  lightness: 0.3020297456532717
  saturation: 0.9462879977654666
  rhythmicContrast: 0.3454257829580456
purpose: []
