name: Simple Inked
favicon: null
layout_spectrum: 0.8998513426631689
typography_spectrum: 0.0579357894603163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6662494314368814
  lightness: 0.3020297456532717
  saturation: 0.9462879977654666
  rhythmicContrast: 0.3454257829580456
purpose: []
