name: Simple Inked
favicon: null
layout_spectrum: 0.65105
typography_spectrum: 0.84298
title: Simple Inked
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#85878a'
    - '#d71825'
    - '#afb0b2'
    - '#e4676f'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.3454258
purpose: []
